services:
  # Dịch vụ MySQL
  llm_chat_sql_db:
    image: mysql:8.2.0
    container_name: mysql_db
    ports:
      - "8019:3306"   # Ánh xạ cổng bên ngoài (8019) đến cổng mặc định (3306) bên trong container
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=chat
    networks:
      - llm_network

  # Dịch vụ khởi tạo Database
  db_initializer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db_initializer
    depends_on:
      - llm_chat_sql_db
    environment:
      - MYSQL_HOST=mysql_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=chat
      - MYSQL_PORT=3306    # Cổng nội bộ của container là 3306
    networks:
      - llm_network

networks:
  llm_network:
